routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('schools', 'SchoolController');

app/School.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class School extends Model
{
    protected $primaryKey = 'school_id';
    protected $fillable = [
    	'school_name',
    	'address',
    	'telephone',
    	'email',
    	'website',
    	'male_students',
    	'female_students',
    	'total_students',
    	'regular_faculty',
    	'parttime_faculty',
    	'total_faculty'];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/SchoolController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\School;
use DB;
use DataTables;

class SchoolController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $data = School::latest()->get();
            return Datatables::of($data)
            ->addIndexColumn()
            ->addColumn('action', function($row){
                   $btn = '<a href="javascript:void(0)" data-toggle="tooltip"  data-id="'.$row->school_id.'" data-original-title="Edit" class="edit btn btn-warning btn-sm editSchool">Update</a>';
                   $btn = $btn.' <a href="javascript:void(0)" data-toggle="tooltip"  data-id="'.$row->school_id.'" data-original-title="Delete" class="btn btn-danger btn-sm deleteSchool">Delete</a>';

                    return $btn;
            })
            ->rawColumns(['action'])
            ->make(true);
        }
      
        return view('schools');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        School::updateOrCreate(['school_id' => $request->school_id], [
            'school_name' => $request->get('school_name'),
            'address' => $request->get('address'),
            'telephone' => $request->get('telephone'),
            'email' => $request->get('email'),
            'website' => $request->get('website'),
            'male_students' => $request->get('male_students'),
            'female_students' => $request->get('female_students'),
            'total_students' => $request->get('total_students'),
            'regular_faculty' => $request->get('regular_faculty'),
            'parttime_faculty' => $request->get('parttime_faculty'),
            'total_faculty' => $request->get('total_faculty')]);        
   
        return response()->json(['success'=>'School saved successfully.']);

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($school_id)
    {
        $school = School::find($school_id);
        return response()->json($school);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($school_id)
    {
        School::find($school_id)->delete();
        return response()->json(['success'=>'School deleted successfully.']);
    }
}

resources/views/schools.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Web App Project</title>
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css" />
    <link href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>  
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.js"></script>


    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!--datatables-->
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
</head>

<style>
  body {
    background-color: #ddd;
  }

  .card {
    padding: 25px;
  }

</style>


<body>
<div class="container">
    <br><br>
    <a class="btn btn-info" href="javascript:void(0)" id="createNewSchool"> Create New School</a>
    <br><br>
    <div class="card">
    <table class="table data-table">
        <thead class="thead-light">
            <tr>
                <th>School</th>
                <th>Address</th>
                <th>Telephone Num</th>
                <th width="150px">Action</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>
</div>
   
<div class="modal fade" id="schModal" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="modelHeading"></h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="SchoolForm" name="SchoolForm" class="form-horizontal">
                   <input type="hidden" name="school_id" id="school_id">
                   <div class="row">
                      <div class="col-md-12">
                        <label for="name" class="control-label">Name</label>
                        <input type="text" class="form-control schlfrm" id="school_name" name="school_name" value="" required=""><br>
                      </div>

                    <div class="col-md-12">
                        <label for="address" class="control-label">Address</label>
                        <input type="text" class="form-control schlfrm" id="address" name="address" value="" required=""><br>
                    </div>
                    </div>
                        
                    <div class="row">
                        <div class="col-md-4">
                            <label for="telephone" class="control-label">Telephone</label>
                            <input type="text" class="form-control schlfrm" id="telephone" name="telephone" value="" maxlength="50" required=""><br>
                        </div>
                        <div class="col-md-4">
                            <label for="email" class="control-label">E-mail</label>
                            <input type="email" class="form-control schlfrm" id="email" name="email" value="" maxlength="50" required=""><br>
                        </div>
                        <div class="col-md-4">
                            <label for="website" class="control-label">Website</label>
                            <input type="text" class="form-control schlfrm" id="website" name="website" value="" maxlength="50" required=""><br>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-4">
                            <label for="male_students" class="control-label">Male Students</label>
                            <input type="number" class="form-control schlfrm" id="male_students" name="male_students" value="" maxlength="50" min="0" required=""><br>
                        </div>
                        <div class="col-md-4">
                            <label for="female_students" class="control-label">Female Students</label>
                            <input type="number" class="form-control schlfrm" id="female_students" name="female_students" value="" maxlength="50" min="0" required=""><br>
                        </div>
                        <div class="col-md-4">
                            <label for="total_students" class="control-label">Total Students</label>
                            <input type="number" class="form-control schlfrm" id="total_students" name="total_students" value="" maxlength="50" min="0" required="" readonly><br>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-4">
                            <label for="regular_faculty" class="control-label">Regular Faculty</label>
                            <input type="text" class="form-control schlfrm" id="regular_faculty" name="regular_faculty" value="" maxlength="50" required=""><br>
                        </div>
                        <div class="col-md-4">
                            <label for="parttime_faculty" class="control-label">Parttime Faculty</label>
                            <input type="text" class="form-control schlfrm" id="parttime_faculty" name="parttime_faculty" value="" maxlength="50" required=""><br>
                        </div>
                        <div class="col-md-4">
                            <label for="total_faculty" class="control-label">Total Faculty</label>
                            <input type="text" class="form-control schlfrm" id="total_faculty" name="total_faculty" value="" maxlength="50" required="" readonly><br>
                        </div>
                    </div>

                    <p id="demo"></p>
      
                    <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                     <button type="submit" class="btn btn-primary" id="saveBtn" value="create" onclick="formValidation()">Save
                     </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    function formValidation() {
      var x = document.getElementsById("school_name").required;
      document.getElementById("demo").innerHTML = x;
    }
</script>

<script type="text/javascript">
  $(function () {
     
      $.ajaxSetup({
          headers: {
              'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
          }
    });
    
    var table = $('.data-table').DataTable({
        processing: true,
        serverSide: true,
        ajax: "{{ route('schools.index') }}",
        columns: [
            {data: 'school_name', school_name: 'school_name'},
            {data: 'address', name: 'address'},
            {data: 'telephone', name: 'telephone'},
            {data: 'action', name: 'action', orderable: false, searchable: false},
        ]
    });
     
    $('#createNewSchool').click(function () {
        $('#saveBtn').val("create-school");
        $('#school_id').val('');
        $('#SchoolForm').trigger("reset");
        $('#modelHeading').html("Create New School");
        $('#schModal').modal('show');
    });
    
    $('body').on('click', '.editSchool', function () {
      var school_id = $(this).data('id');
      $.get("{{ route('schools.index') }}" +'/' + school_id +'/edit', function (data) {
          $('#modelHeading').html("Edit School");
          $('#saveBtn').val("edit-school");
          $('#schModal').modal('show');
          $('#school_id').val(data.school_id);
          $('#school_name').val(data.school_name);
          $('#address').val(data.address);
          $('#telephone').val(data.telephone);
          $('#email').val(data.email);
          $('#website').val(data.website);
          $('#male_students').val(data.male_students);
          $('#female_students').val(data.female_students);
          $('#total_students').val(data.total_students);
          $('#regular_faculty').val(data.regular_faculty);
          $('#parttime_faculty').val(data.parttime_faculty);
          $('#total_faculty').val(data.total_faculty);
      })
   });
    
    $('#saveBtn').click(function (e) {
        e.preventDefault();
    
        $.ajax({
          data: $('#SchoolForm').serialize(),
          url: "{{ route('schools.store') }}",
          type: "POST",
          dataType: 'json',
          success: function (data) {
              $('#SchoolForm').trigger("reset");
              $('#schModal').modal('hide');
              table.draw();
         
          },
          error: function (data) {
              console.log('Error:', data);
              $('#saveBtn').html('Save Changes');
          }
      });
    });
    
    $('body').on('click', '.deleteSchool', function () {
        var school_id = $(this).data('id');
        confirm("Are you sure you want to delete?");
      
       $.ajax({
            type: "DELETE",
            url: "{{ route('schools.store') }}"+'/'+school_id,
            success: function (data) {
                table.draw();
            },
            error: function (data) {
                console.log('Error:', data);
            }
        });
    });
     
  });
</script>
    

    <script>
        $('#male_students').on('input',function(){
            var subtotal = 0;
            $('#male_students').each(function(val){
                var currentVal;
                subtotal+=parseInt($(this).val());
            });
            studentTotal();
        })  

        $('#female_students').on('input',function(){
            var subtotal = 0;
            $('#female_students').each(function(val){
                var currentVal;
                subtotal+=parseInt($(this).val());
            });
            studentTotal();
        })

        function studentTotal(){
            var male = parseInt($('#male_students').val());
            var female = parseInt($('#female_students').val());
            $('#total_students').val(male+female);
        }
    </script>

    <script>
        $('#regular_faculty').on('input',function(){
            var subtotal = 0;
            $('#regular_faculty').each(function(val){
                var currentVal;
                subtotal+=parseInt($(this).val());
            });
            facultyTotal();
        })  

        $('#parttime_faculty').on('input',function(){
            var subtotal = 0;
            $('#parttime_faculty').each(function(val){
                var currentVal;
                subtotal+=parseInt($(this).val());
            });
            facultyTotal();
        })

        function facultyTotal(){
            var regular = parseInt($('#regular_faculty').val());
            var parttime = parseInt($('#parttime_faculty').val());
            $('#total_faculty').val(regular+parttime);
        }
    </script>


</body>
</html>